openapi: 3.1.0
info:
  title: CognitiveForge SSE Events (Tier 2)
  version: 2.0.0
  description: |
    Server-Sent Events schema for real-time progress streaming during dialectical synthesis.
    
    **New in Tier 2**:
    - Detailed progress events (keyword extraction, discovery, generation)
    - Agent-specific events with round numbers
    - Paper found events for real-time discovery visibility
    
    **SSE Format**:
    ```
    event: keyword_extraction_complete
    data: {"keywords": ["IIT", "neural correlates"], "count": 4}
    
    event: discovery_paper_found
    data: {"title": "Integrated Information Theory", "url": "https://arxiv.org/abs/..."}
    ```

servers:
  - url: http://localhost:8000
    description: Local development
  - url: https://api.cognitiveforge.ai
    description: Production (future)

paths:
  /api/synthesize:
    post:
      summary: Start dialectical synthesis with SSE streaming
      description: |
        Initiates a multi-agent dialectical synthesis with real-time progress streaming.
        
        **Response**: SSE stream of progress events (event + data)
        **Duration**: 30-120 seconds depending on query complexity
        **Events**: 20-100 events per synthesis (varies by iteration count)
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: Research question to synthesize
                  example: "What is the nature of consciousness?"
                  minLength: 10
                  maxLength: 500
      
      responses:
        '200':
          description: SSE stream of progress events
          content:
            text/event-stream:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/KeywordExtractionStartEvent'
                  - $ref: '#/components/schemas/KeywordExtractionCompleteEvent'
                  - $ref: '#/components/schemas/DiscoveryStartEvent'
                  - $ref: '#/components/schemas/DiscoveryPaperFoundEvent'
                  - $ref: '#/components/schemas/DiscoveryCompleteEvent'
                  - $ref: '#/components/schemas/ThesisGenerationStartEvent'
                  - $ref: '#/components/schemas/ThesisGenerationCompleteEvent'
                  - $ref: '#/components/schemas/CritiqueStartEvent'
                  - $ref: '#/components/schemas/CritiqueCompleteEvent'
                  - $ref: '#/components/schemas/SynthesisStartEvent'
                  - $ref: '#/components/schemas/SynthesisCompleteEvent'
                  - $ref: '#/components/schemas/ErrorEvent'
        
        '400':
          description: Invalid request (query too short, missing fields)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Query must be at least 10 characters"
        
        '500':
          description: Internal server error (LLM API failure, Neo4j down)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Gemini API rate limit exceeded"

components:
  schemas:
    # ────────────────────────────────────────────────────────────────
    # BASE EVENT SCHEMA
    # ────────────────────────────────────────────────────────────────
    BaseEvent:
      type: object
      required:
        - event
        - data
        - timestamp
      properties:
        event:
          type: string
          description: Event type (maps to SSE 'event' field)
        data:
          type: object
          description: Event-specific data
        timestamp:
          type: number
          format: float
          description: Unix timestamp (seconds since epoch)
          example: 1699564320.123
        agent:
          type: string
          enum: [Analyst, Skeptic, Synthesizer]
          description: Agent name (optional, present for agent-specific events)
        round_number:
          type: integer
          minimum: 1
          description: Current round in debate (1-indexed, optional)
    
    # ────────────────────────────────────────────────────────────────
    # KEYWORD EXTRACTION EVENTS
    # ────────────────────────────────────────────────────────────────
    KeywordExtractionStartEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: keyword_extraction_start
            data:
              type: object
              properties:
                claim:
                  type: string
                  description: Claim to extract keywords from
                  example: "Consciousness arises from integrated information processing"
    
    KeywordExtractionCompleteEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: keyword_extraction_complete
            data:
              type: object
              required:
                - keywords
                - count
              properties:
                keywords:
                  type: array
                  items:
                    type: string
                  description: Extracted multi-word keywords
                  example: ["integrated information theory", "neural correlates", "qualia", "binding problem"]
                  minItems: 3
                  maxItems: 8
                count:
                  type: integer
                  description: Number of keywords extracted
                  example: 4
    
    # ────────────────────────────────────────────────────────────────
    # DISCOVERY EVENTS
    # ────────────────────────────────────────────────────────────────
    DiscoveryStartEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: discovery_start
            data:
              type: object
              required:
                - source
                - query
              properties:
                source:
                  type: string
                  enum: [arxiv, semantic_scholar]
                  description: Discovery source
                query:
                  type: string
                  description: Search query (keyword)
                  example: "integrated information theory"
    
    DiscoveryPaperFoundEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: discovery_paper_found
            data:
              type: object
              required:
                - title
                - url
                - source
              properties:
                title:
                  type: string
                  description: Paper title
                  example: "Integrated Information Theory of Consciousness"
                url:
                  type: string
                  format: uri
                  description: Paper URL
                  example: "https://arxiv.org/abs/1405.7089"
                source:
                  type: string
                  enum: [arxiv, semantic_scholar]
                  description: Discovery source
    
    DiscoveryCompleteEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: discovery_complete
            data:
              type: object
              required:
                - total
                - duplicates
                - added
              properties:
                total:
                  type: integer
                  description: Total papers discovered
                  example: 5
                duplicates:
                  type: integer
                  description: Duplicate papers (already in KG)
                  example: 1
                added:
                  type: integer
                  description: New papers added to KG
                  example: 4
    
    # ────────────────────────────────────────────────────────────────
    # THESIS GENERATION EVENTS
    # ────────────────────────────────────────────────────────────────
    ThesisGenerationStartEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: thesis_generation_start
            data:
              type: object
              properties:
                evidence_count:
                  type: integer
                  description: Number of papers in evidence pool
                  example: 8
    
    ThesisGenerationCompleteEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: thesis_generation_complete
            data:
              type: object
              required:
                - confidence
                - claim
              properties:
                confidence:
                  type: number
                  format: float
                  minimum: 0
                  maximum: 1
                  description: Confidence score (0-1)
                  example: 0.87
                claim:
                  type: string
                  description: Generated thesis claim (truncated to 200 chars for event)
                  example: "Consciousness arises from integrated information processing..."
                  maxLength: 200
    
    # ────────────────────────────────────────────────────────────────
    # CRITIQUE EVENTS
    # ────────────────────────────────────────────────────────────────
    CritiqueStartEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: critique_start
            data:
              type: object
              properties:
                thesis_claim:
                  type: string
                  description: Thesis being critiqued (truncated)
                  example: "Consciousness arises from..."
                  maxLength: 200
    
    CritiqueCompleteEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: critique_complete
            data:
              type: object
              required:
                - contradiction_found
              properties:
                contradiction_found:
                  type: boolean
                  description: True if Skeptic found contradictions
                  example: true
                critique:
                  type: string
                  description: Critique summary (truncated)
                  example: "IIT framework criticized for..."
                  maxLength: 200
                counter_evidence_count:
                  type: integer
                  description: Number of counter-evidence papers found
                  example: 3
    
    # ────────────────────────────────────────────────────────────────
    # SYNTHESIS EVENTS
    # ────────────────────────────────────────────────────────────────
    SynthesisStartEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: synthesis_start
            data:
              type: object
              properties:
                rounds_completed:
                  type: integer
                  description: Number of dialectical rounds completed
                  example: 3
                total_papers:
                  type: integer
                  description: Total papers in knowledge pool
                  example: 18
    
    SynthesisCompleteEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: synthesis_complete
            data:
              type: object
              required:
                - confidence
                - novelty
                - insight
              properties:
                confidence:
                  type: number
                  format: float
                  minimum: 0
                  maximum: 100
                  description: Confidence score (0-100)
                  example: 85
                novelty:
                  type: number
                  format: float
                  minimum: 0
                  maximum: 100
                  description: Novelty score (0-100)
                  example: 72
                insight:
                  type: string
                  description: Final synthesis insight (truncated)
                  example: "Consciousness arises from integrated information processing with causal power..."
                  maxLength: 300
                word_count:
                  type: integer
                  description: Total word count of synthesis (Tier 2 target: 800-1500)
                  example: 1247
    
    # ────────────────────────────────────────────────────────────────
    # ERROR EVENT
    # ────────────────────────────────────────────────────────────────
    ErrorEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          properties:
            event:
              const: error
            data:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: Human-readable error message
                  example: "Gemini API rate limit exceeded. Retrying in 60 seconds..."
                error_type:
                  type: string
                  enum: [api_error, validation_error, discovery_error, kg_error]
                  description: Error category
                recoverable:
                  type: boolean
                  description: True if system can recover (e.g., retry)
                  example: true

# ────────────────────────────────────────────────────────────────────
# EXAMPLE SSE STREAM (FULL SYNTHESIS)
# ────────────────────────────────────────────────────────────────────
# 
# event: keyword_extraction_start
# data: {"claim": "What is consciousness?"}
# 
# event: keyword_extraction_complete
# data: {"keywords": ["integrated information theory", "neural correlates", "qualia"], "count": 3}
# 
# event: discovery_start
# data: {"source": "arxiv", "query": "integrated information theory"}
# 
# event: discovery_paper_found
# data: {"title": "Integrated Information Theory", "url": "https://arxiv.org/abs/1405.7089", "source": "arxiv"}
# 
# event: discovery_paper_found
# data: {"title": "Neural Correlates of Consciousness", "url": "https://arxiv.org/abs/...", "source": "arxiv"}
# 
# event: discovery_complete
# data: {"total": 5, "duplicates": 0, "added": 5}
# 
# event: thesis_generation_start
# data: {"evidence_count": 5}
# 
# event: thesis_generation_complete
# data: {"confidence": 0.87, "claim": "Consciousness arises from integrated information processing..."}
# 
# event: critique_start
# data: {"thesis_claim": "Consciousness arises from..."}
# 
# event: critique_complete
# data: {"contradiction_found": true, "critique": "IIT criticized for...", "counter_evidence_count": 3}
# 
# ... (repeat for rounds 2, 3, etc.)
# 
# event: synthesis_start
# data: {"rounds_completed": 3, "total_papers": 18}
# 
# event: synthesis_complete
# data: {"confidence": 85, "novelty": 72, "insight": "Consciousness arises from...", "word_count": 1247}
# 
# ────────────────────────────────────────────────────────────────────

